"""adicionar regras de agendamento

Revision ID: 042cb2b0831d
Revises: 519d3fb08ba6
Create Date: 2025-09-05 12:32:00.264829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '042cb2b0831d'
down_revision = '519d3fb08ba6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('antecedencia_minima_horas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('janela_maxima_dias', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_column('janela_maxima_dias')
        batch_op.drop_column('antecedencia_minima_horas')

    # ### end Alembic commands ###
