"""Atualizar modelo UsuarioAdmin

Revision ID: 0b19496ad248
Revises: edbd947b53c1
Create Date: 2025-09-07 10:03:30.595915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b19496ad248'
down_revision = 'edbd947b53c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Primeiro, adicionamos as colunas como nullable
    with op.batch_alter_table('usuarios_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('funcao', sa.String(length=20), nullable=True))
    
    # Atualizamos os registros existentes
    conn = op.get_bind()
    conn.execute(sa.text(
        "UPDATE usuarios_admin SET username = email, "
        "password_hash = senha_hash, "
        "funcao = 'utilizador'"
    ))
    
    # Agora alteramos as colunas para not nullable e finalizamos as alterações
    with op.batch_alter_table('usuarios_admin', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('funcao',
               existing_type=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.create_unique_constraint('uq_usuarios_admin_username', ['username'])
        batch_op.drop_column('senha_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('senha_hash', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_constraint('uq_usuarios_admin_username', type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('funcao')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
