"""adicionar opcoes de personalizacao visual

Revision ID: 1243debdd716
Revises: 042cb2b0831d
Create Date: 2025-09-05 12:46:20.340206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1243debdd716'
down_revision = '042cb2b0831d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor_secundaria', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('favicon_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_column('favicon_url')
        batch_op.drop_column('cor_secundaria')

    # ### end Alembic commands ###
