"""Adicionar modelo Configuracao

Revision ID: 263c69241b50
Revises: 38ae5256a83e
Create Date: 2025-09-05 10:56:57.658117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263c69241b50'
down_revision = '38ae5256a83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_barbearia', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('cor_primaria', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
