"""adicionar tabela dias_semana

Revision ID: 38ae5256a83e
Revises: 86a997d5a2dc
Create Date: 2025-09-04 16:49:42.255014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38ae5256a83e'
down_revision = '86a997d5a2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dias_semana',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=20), nullable=False),
    sa.Column('hora_abertura', sa.Time(), nullable=False),
    sa.Column('hora_fechamento', sa.Time(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dias_semana')
    # ### end Alembic commands ###
