"""adicionar_coluna_funcao_usuario_admin

Revision ID: 422e395c2b54
Revises: 1243debdd716
Create Date: 2025-09-05 15:43:46.876857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422e395c2b54'
down_revision = '1243debdd716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funcao', sa.String(length=20), nullable=True))
    
    # Atualizar registros existentes para ter o valor padrão 'utilizador'
    op.execute("UPDATE usuarios_admin SET funcao = 'utilizador' WHERE funcao IS NULL")
    
    # Tornar a coluna NOT NULL após atualizar os valores
    with op.batch_alter_table('usuarios_admin', schema=None) as batch_op:
        batch_op.alter_column('funcao', nullable=False, existing_type=sa.String(length=20))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios_admin', schema=None) as batch_op:
        batch_op.drop_column('funcao')

    # ### end Alembic commands ###
