"""Adicionar campos de contato

Revision ID: 519d3fb08ba6
Revises: 263c69241b50
Create Date: 2025-09-05 11:16:15.107084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519d3fb08ba6'
down_revision = '263c69241b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('link_instagram', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('link_facebook', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_column('link_facebook')
        batch_op.drop_column('link_instagram')
        batch_op.drop_column('endereco')
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
