"""adicionar_especialidade_barbeiros

Revision ID: 86a997d5a2dc
Revises: de7e89a7d0ed
Create Date: 2025-09-04 16:33:39.930186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86a997d5a2dc'
down_revision = 'de7e89a7d0ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbeiros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('especialidade', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbeiros', schema=None) as batch_op:
        batch_op.drop_column('especialidade')

    # ### end Alembic commands ###
