"""adicionar_campos_financeiros_agendamento

Revision ID: 976a449d8b6a
Revises: c2c289c8807a
Create Date: 2025-09-09 21:38:41.949525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976a449d8b6a'
down_revision = 'c2c289c8807a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_pago', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('metodo_pagamento', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos', schema=None) as batch_op:
        batch_op.drop_column('metodo_pagamento')
        batch_op.drop_column('valor_pago')

    # ### end Alembic commands ###
