"""adicionar_colunas_twilio_integracao

Revision ID: a69c3d09f673
Revises: 0b19496ad248
Create Date: 2025-09-09 17:25:20.290678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69c3d09f673'
down_revision = '0b19496ad248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twilio_account_sid', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twilio_auth_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('twilio_whatsapp_number', sa.String(length=20), nullable=True))

    with op.batch_alter_table('usuarios_admin', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('uq_usuarios_admin_username'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios_admin', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_usuarios_admin_username'), ['username'])
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_column('twilio_whatsapp_number')
        batch_op.drop_column('twilio_auth_token')
        batch_op.drop_column('twilio_account_sid')

    # ### end Alembic commands ###
