"""adicionar_colunas_motor_agenda

Revision ID: a8ce65c8a626
Revises: a69c3d09f673
Create Date: 2025-09-09 18:21:45.777920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8ce65c8a626'
down_revision = 'a69c3d09f673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervalo_slot_minutos', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tempo_preparacao_minutos', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_column('tempo_preparacao_minutos')
        batch_op.drop_column('intervalo_slot_minutos')

    # ### end Alembic commands ###
