"""Adicionar coluna exibir_redes_sociais

Revision ID: c2c289c8807a
Revises: a8ce65c8a626
Create Date: 2025-09-09 20:10:25.992282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c289c8807a'
down_revision = 'a8ce65c8a626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exibir_redes_sociais', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.drop_column('exibir_redes_sociais')

    # ### end Alembic commands ###
