"""Adicionar coluna imagem_url ao modelo Servico

Revision ID: e6b36af0bf18
Revises: 422e395c2b54
Create Date: 2025-09-05 21:08:18.028954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b36af0bf18'
down_revision = '422e395c2b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('usuarios_admin', schema=None) as batch_op:
        batch_op.drop_column('funcao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios_admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funcao', sa.VARCHAR(length=20), nullable=False))

    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.drop_column('imagem_url')

    # ### end Alembic commands ###
