"""Adicionar coluna foto_url ao modelo Barbeiro

Revision ID: edbd947b53c1
Revises: e6b36af0bf18
Create Date: 2025-09-06 02:30:43.366196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbd947b53c1'
down_revision = 'e6b36af0bf18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbeiros', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbeiros', schema=None) as batch_op:
        batch_op.drop_column('foto_url')

    # ### end Alembic commands ###
